enabled: true

storageClass:
  name: treadstone-workspace
  annotations: {}
  labels: {}
  provisioner: ""  # always overridden by values-<profile>.yaml (local / ack / aws)
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
  parameters: {}
