replicaCount: 1

image:
  repository: ghcr.io/earayu/treadstone
  tag: latest
  pullPolicy: Always

env:
  TREADSTONE_DEBUG: "false"
  TREADSTONE_AUTH_TYPE: "cookie"
  TREADSTONE_SANDBOX_DOMAIN: ""
  TREADSTONE_SANDBOX_NAMESPACE: "treadstone"

envSecretRef: treadstone-secrets

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: false
