replicaCount: 2

image:
  repository: ""
  tag: ""
  pullPolicy: Always

envSecretRef: treadstone-secrets

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

migration:
  enabled: true

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
