replicaCount: 1

image:
  repository: ghcr.io/earayu/treadstone
  tag: latest
  pullPolicy: Always

envSecretRef: treadstone-secrets

service:
  type: LoadBalancer
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

migration:
  enabled: true

hpa:
  enabled: false

ingress:
  enabled: false
