[supervisord]
nodaemon=true
pidfile=%(ENV_XDG_RUNTIME_DIR)s/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0
loglevel=info

[unix_http_server]
file=%(ENV_XDG_RUNTIME_DIR)s/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix://%(ENV_XDG_RUNTIME_DIR)s/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:tigervnc]
command=/usr/bin/Xtigervnc %(ENV_DISPLAY)s -depth %(ENV_DISPLAY_DEPTH)s -geometry %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)s -localhost -rfbport %(ENV_VNC_SERVER_PORT)s -AlwaysShared -SecurityTypes None
priority=100
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/vnc.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:openbox]
command=/opt/gem/openbox.sh
priority=200
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/openbox.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:browser]
command=/opt/gem/start-browser.sh
priority=300
autorestart=true
stopsignal=INT
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/browser.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:websocat]
command=/usr/local/bin/websocat --binary --exit-on-eof --ping-interval 30 ws-l:127.0.0.1:%(ENV_WEBSOCKET_PROXY_PORT)s tcp:127.0.0.1:%(ENV_VNC_SERVER_PORT)s
priority=300
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/websocat.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:gem-server]
command=/usr/local/bin/gem-server --host 127.0.0.1 --port %(ENV_GEM_SERVER_PORT)s --cdp-origin http://127.0.0.1:%(ENV_BROWSER_REMOTE_DEBUGGING_PORT)s
priority=400
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/gem-server.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:python-server]
command=/usr/local/bin/python -m app.cli --host 127.0.0.1 --port %(ENV_SANDBOX_SRV_PORT)s --workspace %(ENV_HOME)s
priority=400
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/python-server.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2

[program:nginx]
command=/opt/gem/nginx-wait.sh
priority=500
autorestart=true
redirect_stderr=true
stdout_logfile=%(ENV_LOG_DIR)s/nginx.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
