# User and Group are handled by supervisord
# User nobody
# Group nogroup
Port ${TINYPROXY_PORT}
Timeout 600
DefaultErrorFile "/usr/local/share/tinyproxy/default.html"
LogLevel Info
PidFile "${XDG_RUNTIME_DIR}/tinyproxy.pid"
MaxClients 100
ViaProxyName "tinyproxy"

Allow 0.0.0.0/0
