namespace: agent-sandbox-system

controller:
  image:
    repository: registry.k8s.io/agent-sandbox/agent-sandbox-controller
    tag: v1.0.3
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
