"""add k8s_sandbox_claim_name and make image nullable

Revision ID: 0049d56201ad
Revises: 7d32ba24d363
Create Date: 2026-03-19 22:31:10.640828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0049d56201ad'
down_revision: Union[str, Sequence[str], None] = '7d32ba24d363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox', sa.Column('k8s_sandbox_claim_name', sa.String(length=255), nullable=True))
    op.alter_column('sandbox', 'image',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_index(op.f('ix_sandbox_k8s_sandbox_claim_name'), 'sandbox', ['k8s_sandbox_claim_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_k8s_sandbox_claim_name'), table_name='sandbox')
    op.alter_column('sandbox', 'image',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('sandbox', 'k8s_sandbox_claim_name')
    # ### end Alembic commands ###
