"""add cli_login_flow table

Revision ID: 2457b93fc846
Revises: d68520294aa5
Create Date: 2026-03-26 18:50:20.000857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2457b93fc846'
down_revision: Union[str, Sequence[str], None] = 'd68520294aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli_login_flow',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('flow_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_completed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_login_flow_status_expires', 'cli_login_flow', ['status', 'gmt_expires'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cli_login_flow_status_expires', table_name='cli_login_flow')
    op.drop_table('cli_login_flow')
    # ### end Alembic commands ###
