"""add waitlist application table

Revision ID: 28823e70456d
Revises: a1b2c3d4e5f8
Create Date: 2026-03-30 18:42:36.696720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28823e70456d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_application',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_tier', sa.String(length=16), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_application_email', 'waitlist_application', ['email'], unique=False)
    op.create_index('ix_waitlist_application_status', 'waitlist_application', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_application_status', table_name='waitlist_application')
    op.drop_index('ix_waitlist_application_email', table_name='waitlist_application')
    op.drop_table('waitlist_application')
    # ### end Alembic commands ###
