"""add sandbox table

Revision ID: 7d32ba24d363
Revises: a30f8dfeb16e
Create Date: 2026-03-19 21:39:39.256917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d32ba24d363'
down_revision: Union[str, Sequence[str], None] = 'a30f8dfeb16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=24), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=False),
    sa.Column('runtime_type', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_stop_interval', sa.Integer(), nullable=False),
    sa.Column('auto_delete_interval', sa.Integer(), nullable=False),
    sa.Column('k8s_sandbox_name', sa.String(length=255), nullable=True),
    sa.Column('k8s_namespace', sa.String(length=255), nullable=False),
    sa.Column('k8s_resource_version', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('endpoints', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_stopped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_name'), 'sandbox', ['name'], unique=True)
    op.create_index(op.f('ix_sandbox_owner_id'), 'sandbox', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_owner_id'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_name'), table_name='sandbox')
    op.drop_table('sandbox')
    # ### end Alembic commands ###
