"""add email_verification_log table

Revision ID: 90759a4d649a
Revises: a5f9b2c17d61
Create Date: 2026-03-28 19:29:53.706873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90759a4d649a'
down_revision: Union[str, Sequence[str], None] = 'a5f9b2c17d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_log',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('verify_url', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evl_user_id_gmt_created', 'email_verification_log', ['user_id', 'gmt_created'])
    op.create_index('ix_evl_email', 'email_verification_log', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evl_email', table_name='email_verification_log')
    op.drop_index('ix_evl_user_id_gmt_created', table_name='email_verification_log')
    op.drop_table('email_verification_log')
    # ### end Alembic commands ###
