"""add metering tables

Revision ID: 9f3a6a152a5c
Revises: 2457b93fc846
Create Date: 2026-03-27 00:03:20.715005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f3a6a152a5c'
down_revision: Union[str, Sequence[str], None] = '2457b93fc846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_template',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tier_name', sa.String(length=16), nullable=False),
    sa.Column('compute_credits_monthly', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('storage_credits_monthly', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_running', sa.Integer(), nullable=False),
    sa.Column('max_sandbox_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_templates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('grace_period_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('credit_grant',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('credit_type', sa.String(length=16), nullable=False),
    sa.Column('grant_type', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.String(length=24), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_grant_expires', 'credit_grant', ['expires_at'], unique=False, postgresql_where=sa.text('remaining_amount > 0'))
    op.create_index('ix_credit_grant_user_type', 'credit_grant', ['user_id', 'credit_type'], unique=False)
    op.create_table('user_plan',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('compute_credits_monthly_limit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('storage_credits_monthly_limit', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_running', sa.Integer(), nullable=False),
    sa.Column('max_sandbox_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_templates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('grace_period_seconds', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compute_credits_monthly_used', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('overrides', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('grace_period_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_80_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_100_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('compute_session',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('template', sa.String(length=32), nullable=False),
    sa.Column('credit_rate_per_hour', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_metered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credits_consumed', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('credits_consumed_monthly', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('credits_consumed_extra', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compute_session_open', 'compute_session', ['ended_at'], unique=False, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index(op.f('ix_compute_session_sandbox_id'), 'compute_session', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_compute_session_user_id'), 'compute_session', ['user_id'], unique=False)
    op.create_table('storage_ledger',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=True),
    sa.Column('size_gib', sa.Integer(), nullable=False),
    sa.Column('storage_state', sa.String(length=16), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gib_hours_consumed', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('last_metered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_ledger_sandbox', 'storage_ledger', ['sandbox_id'], unique=False)
    op.create_index('ix_storage_ledger_user_state', 'storage_ledger', ['user_id', 'storage_state'], unique=False)
    # ### end Alembic commands ###

    # Seed TierTemplate default rows
    op.execute(sa.text("""
        INSERT INTO tier_template
            (id, tier_name, compute_credits_monthly, storage_credits_monthly,
             max_concurrent_running, max_sandbox_duration_seconds, allowed_templates,
             grace_period_seconds, is_active, gmt_created, gmt_updated)
        VALUES
            ('tt_seed_free_00001', 'free',       10,   0,   1, 1800,  '["tiny","small"]',                          600,  TRUE, NOW(), NOW()),
            ('tt_seed_pro_000001', 'pro',        100,  10,  3, 7200,  '["tiny","small","medium"]',                  1800, TRUE, NOW(), NOW()),
            ('tt_seed_ultra_0001', 'ultra',      300,  20,  5, 28800, '["tiny","small","medium","large"]',          3600, TRUE, NOW(), NOW()),
            ('tt_seed_enterp_001', 'enterprise', 5000, 500, 50,86400, '["tiny","small","medium","large","xlarge"]', 7200, TRUE, NOW(), NOW())
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_storage_ledger_user_state', table_name='storage_ledger')
    op.drop_index('ix_storage_ledger_sandbox', table_name='storage_ledger')
    op.drop_table('storage_ledger')
    op.drop_index(op.f('ix_compute_session_user_id'), table_name='compute_session')
    op.drop_index(op.f('ix_compute_session_sandbox_id'), table_name='compute_session')
    op.drop_index('ix_compute_session_open', table_name='compute_session', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('compute_session')
    op.drop_table('user_plan')
    op.drop_index('ix_credit_grant_user_type', table_name='credit_grant')
    op.drop_index('ix_credit_grant_expires', table_name='credit_grant', postgresql_where=sa.text('remaining_amount > 0'))
    op.drop_table('credit_grant')
    op.drop_table('tier_template')
    # ### end Alembic commands ###
