"""rename k8s_claim_name to k8s_sandbox_claim_name and add api_key expires

Revision ID: a54ae0733978
Revises: 0049d56201ad
Create Date: 2026-03-19 23:28:49.462050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54ae0733978'
down_revision: Union[str, Sequence[str], None] = '0049d56201ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'gmt_expires')
    # ### end Alembic commands ###
