"""add provision_mode persist storage_size to sandbox

Revision ID: bc37bfeef9ac
Revises: a54ae0733978
Create Date: 2026-03-21 16:06:07.555042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc37bfeef9ac'
down_revision: Union[str, Sequence[str], None] = 'a54ae0733978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox', sa.Column('provision_mode', sa.String(length=16), nullable=False, server_default='claim'))
    op.add_column('sandbox', sa.Column('persist', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sandbox', sa.Column('storage_size', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandbox', 'storage_size')
    op.drop_column('sandbox', 'persist')
    op.drop_column('sandbox', 'provision_mode')
    # ### end Alembic commands ###
