"""initial schema

Revision ID: c9d27ea3b835
Revises: 
Create Date: 2026-03-31 10:49:16.592474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d27ea3b835'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.String(length=24), nullable=True),
    sa.Column('actor_api_key_id', sa.String(length=24), nullable=True),
    sa.Column('credential_type', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index('ix_audit_event_action_created_at', 'audit_event', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_api_key_id'), 'audit_event', ['actor_api_key_id'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_type'), 'audit_event', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_user_id'), 'audit_event', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_event_request_id'), 'audit_event', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_event_result'), 'audit_event', ['result'], unique=False)
    op.create_index(op.f('ix_audit_event_target_type'), 'audit_event', ['target_type'], unique=False)
    op.create_index('ix_audit_event_target_type_target_id', 'audit_event', ['target_type', 'target_id'], unique=False)
    op.create_table('tier_template',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('tier_name', sa.String(length=16), nullable=False),
    sa.Column('compute_units_monthly', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('storage_capacity_gib', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_running', sa.Integer(), nullable=False),
    sa.Column('max_sandbox_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_templates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('grace_period_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('has_local_password', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('api_key',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_preview', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('control_plane_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_plane_mode', sa.String(length=16), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_table('cli_login_flow',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('flow_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_completed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cli_login_flow_status_expires', 'cli_login_flow', ['status', 'gmt_expires'], unique=False)
    op.create_table('compute_grant',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('grant_type', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.String(length=24), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compute_grant_expires', 'compute_grant', ['expires_at'], unique=False, postgresql_where=sa.text('remaining_amount > 0'))
    op.create_index('ix_compute_grant_user', 'compute_grant', ['user_id'], unique=False)
    op.create_index('ix_compute_grant_user_expires_active', 'compute_grant', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('remaining_amount > 0'))
    op.create_table('email_verification_log',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('verify_url', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_account',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_name', 'account_id', name='uq_oauth_account_provider_account'),
    sa.UniqueConstraint('user_id', 'oauth_name', name='uq_oauth_account_user_provider')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('sandbox',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=24), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=False),
    sa.Column('runtime_type', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_stop_interval', sa.Integer(), nullable=False),
    sa.Column('auto_delete_interval', sa.Integer(), nullable=False),
    sa.Column('provision_mode', sa.String(length=16), nullable=False),
    sa.Column('persist', sa.Boolean(), nullable=False),
    sa.Column('storage_size', sa.String(length=32), nullable=True),
    sa.Column('k8s_sandbox_claim_name', sa.String(length=255), nullable=True),
    sa.Column('k8s_sandbox_name', sa.String(length=255), nullable=True),
    sa.Column('k8s_namespace', sa.String(length=255), nullable=False),
    sa.Column('k8s_resource_version', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('endpoints', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_stopped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_k8s_sandbox_claim_name'), 'sandbox', ['k8s_sandbox_claim_name'], unique=False)
    op.create_index(op.f('ix_sandbox_k8s_sandbox_name'), 'sandbox', ['k8s_sandbox_name'], unique=False)
    op.create_index(op.f('ix_sandbox_name'), 'sandbox', ['name'], unique=False)
    op.create_index(op.f('ix_sandbox_owner_id'), 'sandbox', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sandbox_status'), 'sandbox', ['status'], unique=False)
    op.create_index('uq_sandbox_owner_name_active', 'sandbox', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.create_table('storage_quota_grant',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('grant_type', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('size_gib', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.String(length=24), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_quota_grant_user', 'storage_quota_grant', ['user_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_feedback_gmt_created', 'user_feedback', ['gmt_created'], unique=False)
    op.create_index('ix_user_feedback_user_id', 'user_feedback', ['user_id'], unique=False)
    op.create_table('user_plan',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('compute_units_monthly_limit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('storage_capacity_limit_gib', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_running', sa.Integer(), nullable=False),
    sa.Column('max_sandbox_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_templates', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('grace_period_seconds', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compute_units_monthly_used', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('compute_units_overage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('overrides', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('grace_period_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_80_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_100_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_plan_period_end'), 'user_plan', ['period_end'], unique=False)
    op.create_table('waitlist_application',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_tier', sa.String(length=16), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_application_email', 'waitlist_application', ['email'], unique=False)
    op.create_index('ix_waitlist_application_status', 'waitlist_application', ['status'], unique=False)
    op.create_table('api_key_sandbox_grant',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('api_key_id', sa.String(length=24), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'sandbox_id', name='uq_api_key_sandbox_grant_key_sandbox')
    )
    op.create_index(op.f('ix_api_key_sandbox_grant_api_key_id'), 'api_key_sandbox_grant', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_sandbox_grant_sandbox_id'), 'api_key_sandbox_grant', ['sandbox_id'], unique=False)
    op.create_table('compute_session',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=False),
    sa.Column('vcpu_request', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('memory_gib_request', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_metered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vcpu_hours', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('memory_gib_hours', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compute_session_open', 'compute_session', ['ended_at'], unique=False, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index(op.f('ix_compute_session_sandbox_id'), 'compute_session', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_compute_session_user_id'), 'compute_session', ['user_id'], unique=False)
    op.create_index('uq_compute_session_sandbox_active', 'compute_session', ['sandbox_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('sandbox_web_link',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sandbox_id', name='uq_sandbox_web_link_sandbox_id')
    )
    op.create_index(op.f('ix_sandbox_web_link_created_by_user_id'), 'sandbox_web_link', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_sandbox_web_link_sandbox_id'), 'sandbox_web_link', ['sandbox_id'], unique=False)
    op.create_table('storage_ledger',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=True),
    sa.Column('size_gib', sa.Integer(), nullable=False),
    sa.Column('storage_state', sa.String(length=16), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gib_hours_consumed', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('last_metered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_ledger_sandbox', 'storage_ledger', ['sandbox_id'], unique=False)
    op.create_index('ix_storage_ledger_sandbox_active', 'storage_ledger', ['sandbox_id'], unique=True, postgresql_where=sa.text("storage_state = 'active'"))
    op.create_index('ix_storage_ledger_user_state', 'storage_ledger', ['user_id', 'storage_state'], unique=False)
    # ### end Alembic commands ###

    # Seed tier_template data
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        sa.table(
            'tier_template',
            sa.column('id', sa.String),
            sa.column('tier_name', sa.String),
            sa.column('compute_units_monthly', sa.Numeric),
            sa.column('storage_capacity_gib', sa.Integer),
            sa.column('max_concurrent_running', sa.Integer),
            sa.column('max_sandbox_duration_seconds', sa.Integer),
            sa.column('allowed_templates', sa.JSON),
            sa.column('grace_period_seconds', sa.Integer),
            sa.column('is_active', sa.Boolean),
            sa.column('gmt_created', sa.DateTime),
            sa.column('gmt_updated', sa.DateTime),
        ),
        [
            {
                'id': 'tier_free',
                'tier_name': 'free',
                'compute_units_monthly': 10.0,
                'storage_capacity_gib': 0,
                'max_concurrent_running': 1,
                'max_sandbox_duration_seconds': 7200,
                'allowed_templates': ['aio-sandbox-tiny'],
                'grace_period_seconds': 900,
                'is_active': True,
                'gmt_created': now,
                'gmt_updated': now,
            },
            {
                'id': 'tier_pro',
                'tier_name': 'pro',
                'compute_units_monthly': 80.0,
                'storage_capacity_gib': 10,
                'max_concurrent_running': 3,
                'max_sandbox_duration_seconds': 28800,
                'allowed_templates': ['aio-sandbox-tiny', 'aio-sandbox-small', 'aio-sandbox-medium'],
                'grace_period_seconds': 3600,
                'is_active': True,
                'gmt_created': now,
                'gmt_updated': now,
            },
            {
                'id': 'tier_ultra',
                'tier_name': 'ultra',
                'compute_units_monthly': 240.0,
                'storage_capacity_gib': 30,
                'max_concurrent_running': 5,
                'max_sandbox_duration_seconds': 86400,
                'allowed_templates': ['aio-sandbox-tiny', 'aio-sandbox-small', 'aio-sandbox-medium'],
                'grace_period_seconds': 10800,
                'is_active': True,
                'gmt_created': now,
                'gmt_updated': now,
            },
            {
                'id': 'tier_custom',
                'tier_name': 'custom',
                'compute_units_monthly': 800.0,
                'storage_capacity_gib': 100,
                'max_concurrent_running': 10,
                'max_sandbox_duration_seconds': 259200,
                'allowed_templates': [
                    'aio-sandbox-tiny',
                    'aio-sandbox-small',
                    'aio-sandbox-medium',
                    'aio-sandbox-large',
                    'aio-sandbox-xlarge',
                ],
                'grace_period_seconds': 43200,
                'is_active': True,
                'gmt_created': now,
                'gmt_updated': now,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_storage_ledger_user_state', table_name='storage_ledger')
    op.drop_index('ix_storage_ledger_sandbox_active', table_name='storage_ledger', postgresql_where=sa.text("storage_state = 'active'"))
    op.drop_index('ix_storage_ledger_sandbox', table_name='storage_ledger')
    op.drop_table('storage_ledger')
    op.drop_index(op.f('ix_sandbox_web_link_sandbox_id'), table_name='sandbox_web_link')
    op.drop_index(op.f('ix_sandbox_web_link_created_by_user_id'), table_name='sandbox_web_link')
    op.drop_table('sandbox_web_link')
    op.drop_index('uq_compute_session_sandbox_active', table_name='compute_session', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_compute_session_user_id'), table_name='compute_session')
    op.drop_index(op.f('ix_compute_session_sandbox_id'), table_name='compute_session')
    op.drop_index('ix_compute_session_open', table_name='compute_session', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('compute_session')
    op.drop_index(op.f('ix_api_key_sandbox_grant_sandbox_id'), table_name='api_key_sandbox_grant')
    op.drop_index(op.f('ix_api_key_sandbox_grant_api_key_id'), table_name='api_key_sandbox_grant')
    op.drop_table('api_key_sandbox_grant')
    op.drop_index('ix_waitlist_application_status', table_name='waitlist_application')
    op.drop_index('ix_waitlist_application_email', table_name='waitlist_application')
    op.drop_table('waitlist_application')
    op.drop_index(op.f('ix_user_plan_period_end'), table_name='user_plan')
    op.drop_table('user_plan')
    op.drop_index('ix_user_feedback_user_id', table_name='user_feedback')
    op.drop_index('ix_user_feedback_gmt_created', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index('ix_storage_quota_grant_user', table_name='storage_quota_grant')
    op.drop_table('storage_quota_grant')
    op.drop_index('uq_sandbox_owner_name_active', table_name='sandbox', postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.drop_index(op.f('ix_sandbox_status'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_owner_id'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_name'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_k8s_sandbox_name'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_k8s_sandbox_claim_name'), table_name='sandbox')
    op.drop_table('sandbox')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_table('email_verification_log')
    op.drop_index('ix_compute_grant_user_expires_active', table_name='compute_grant', postgresql_where=sa.text('remaining_amount > 0'))
    op.drop_index('ix_compute_grant_user', table_name='compute_grant')
    op.drop_index('ix_compute_grant_expires', table_name='compute_grant', postgresql_where=sa.text('remaining_amount > 0'))
    op.drop_table('compute_grant')
    op.drop_index('ix_cli_login_flow_status_expires', table_name='cli_login_flow')
    op.drop_table('cli_login_flow')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tier_template')
    op.drop_index('ix_audit_event_target_type_target_id', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_target_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_result'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_request_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_user_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_type'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_api_key_id'), table_name='audit_event')
    op.drop_index('ix_audit_event_action_created_at', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
