"""remove invitation table and add oauth constraints

Revision ID: d68520294aa5
Revises: b1d94d9b8d42
Create Date: 2026-03-26 14:33:10.449158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68520294aa5'
down_revision: Union[str, Sequence[str], None] = 'b1d94d9b8d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation')
    op.create_unique_constraint('uq_oauth_account_provider_account', 'oauth_account', ['oauth_name', 'account_id'])
    op.create_unique_constraint('uq_oauth_account_user_provider', 'oauth_account', ['user_id', 'oauth_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oauth_account_user_provider', 'oauth_account', type_='unique')
    op.drop_constraint('uq_oauth_account_provider_account', 'oauth_account', type_='unique')
    op.create_table('invitation',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('invitation_pkey')),
    sa.UniqueConstraint('token', name=op.f('invitation_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
