"""add sandbox web links

Revision ID: ec1f57069933
Revises: c8e7a2f0b1d4
Create Date: 2026-03-24 16:08:45.663541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1f57069933'
down_revision: Union[str, Sequence[str], None] = 'c8e7a2f0b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_web_link',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sandbox_id', sa.String(length=24), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sandbox_id', name='uq_sandbox_web_link_sandbox_id')
    )
    op.create_index(op.f('ix_sandbox_web_link_created_by_user_id'), 'sandbox_web_link', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_sandbox_web_link_sandbox_id'), 'sandbox_web_link', ['sandbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_web_link_sandbox_id'), table_name='sandbox_web_link')
    op.drop_index(op.f('ix_sandbox_web_link_created_by_user_id'), table_name='sandbox_web_link')
    op.drop_table('sandbox_web_link')
    # ### end Alembic commands ###
