{{- if .Values.claimAcsScheduling.enabled }}
---
apiVersion: scheduling.alibabacloud.com/v1alpha1
kind: ResourcePolicy
metadata:
  name: sandbox-claim-acs-overflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sandbox-runtime.labels" . | nindent 4 }}
spec:
  selector:
    {{- range $k, $v := .Values.sandboxPodSelectorLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    treadstone-ai.dev/provision-mode: "claim"
  strategy: prefer
  units:
    {{- toYaml .Values.claimAcsScheduling.units | nindent 4 }}
{{- end }}

{{- if .Values.directAcsScheduling.enabled }}
---
apiVersion: scheduling.alibabacloud.com/v1alpha1
kind: ResourcePolicy
metadata:
  name: sandbox-direct-acs-overflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sandbox-runtime.labels" . | nindent 4 }}
spec:
  selector:
    {{- range $k, $v := .Values.sandboxPodSelectorLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    treadstone-ai.dev/provision-mode: "direct"
  strategy: prefer
  units:
    {{- toYaml .Values.directAcsScheduling.units | nindent 4 }}
{{- end }}
