#!/usr/bin/env python3
"""
Post-process Hurl's HTML report into a grouped, visually-enhanced version.

Reads the raw index.html generated by `hurl --report-html`, groups rows
by run (same data-timestamp = same run), and writes a new index.html with
modern styling and collapsible per-run sections.

Usage:
    python scripts/gen-e2e-report.py [REPORT_DIR]
    REPORT_DIR defaults to reports/e2e
"""

import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

# ── Parsing ────────────────────────────────────────────────────────────────────

# Hurl 5.x: detail HTML lives under report_dir/store/; index links use store/<uuid>-*.html.
# Some versions or merges may omit data-timestamp; treat as 0 so rows still group.
_TR_RE = re.compile(r"<tr(?:\s[^>]*)?>.*?</tr>", re.DOTALL)

_SOURCE_HREF_RES = (
    re.compile(r'href="(store/[^"]+source\.html)"'),
    re.compile(r'href="([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}-source\.html)"'),
)

_TIMELINE_HREF_RES = (
    re.compile(r'href="(store/[^"]+timeline\.html)"'),
    re.compile(r'href="([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}-timeline\.html)"'),
)


def _first_href(cell: str, patterns: tuple[re.Pattern[str], ...]) -> str:
    for pat in patterns:
        m = pat.search(cell)
        if m:
            return m.group(1)
    return ""


def parse_rows(html: str) -> list[dict]:
    rows = []
    for tr_match in _TR_RE.finditer(html):
        tr = tr_match.group()

        def attr(name: str) -> str:
            m = re.search(rf'data-{name}="([^"]+)"', tr)
            return m.group(1) if m else ""

        ts_raw = attr("timestamp")
        timestamp = int(ts_raw) if ts_raw != "" else 0

        cells = re.findall(r"<td[^>]*>(.*?)</td>", tr, re.DOTALL)
        if len(cells) < 4:
            continue

        source_href = _first_href(cells[0], _SOURCE_HREF_RES)
        timeline_href = _first_href(cells[1], _TIMELINE_HREF_RES)
        if not source_href or not timeline_href:
            continue

        rows.append(
            {
                "timestamp": timestamp,
                "status": attr("status"),
                "filename": attr("filename"),
                "short_name": Path(attr("filename")).name,
                "duration_ms": int(attr("duration") or 0),
                "source_href": source_href,
                "timeline_href": timeline_href,
                "start_time": re.sub(r"<[^>]+>", "", cells[2]).strip(),
                "duration_s": re.sub(r"<[^>]+>", "", cells[3]).strip(),
            }
        )
    return rows


# ── HTML generation ────────────────────────────────────────────────────────────

CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg: #f8f9fb;
  --surface: #ffffff;
  --border: #e2e5eb;
  --text: #1a1d23;
  --text-muted: #6b7280;
  --accent: #6366f1;
  --pass: #16a34a;
  --pass-bg: #dcfce7;
  --fail: #dc2626;
  --fail-bg: #fee2e2;
  --run-pass-border: #86efac;
  --run-fail-border: #fca5a5;
  --shadow: 0 1px 3px rgba(0,0,0,.08), 0 1px 2px rgba(0,0,0,.04);
  --radius: 10px;
  --font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  --mono: "SF Mono", "Fira Code", Consolas, monospace;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0f1117;
    --surface: #1a1d27;
    --border: #2d3142;
    --text: #e2e4ec;
    --text-muted: #8b93a8;
    --pass: #4ade80;
    --pass-bg: #052e16;
    --fail: #f87171;
    --fail-bg: #2d0a0a;
    --run-pass-border: #166534;
    --run-fail-border: #7f1d1d;
    --shadow: 0 1px 3px rgba(0,0,0,.4);
  }
}

body {
  font-family: var(--font);
  font-size: 14px;
  line-height: 1.5;
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
}

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

/* ── Layout ── */

.container {
  max-width: 1100px;
  margin: 0 auto;
  padding: 32px 24px 64px;
}

/* ── Header ── */

.report-header {
  margin-bottom: 32px;
}

.report-header h1 {
  font-size: 26px;
  font-weight: 700;
  letter-spacing: -.5px;
  color: var(--text);
  margin-bottom: 20px;
}

.stats-row {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.stat-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 14px 20px;
  min-width: 110px;
  box-shadow: var(--shadow);
}

.stat-card .value {
  display: block;
  font-size: 28px;
  font-weight: 700;
  line-height: 1;
  margin-bottom: 4px;
}

.stat-card .label {
  display: block;
  font-size: 12px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: .06em;
}

.stat-card.pass .value { color: var(--pass); }
.stat-card.fail .value { color: var(--fail); }

/* ── Run sections ── */

.runs { display: flex; flex-direction: column; gap: 12px; }

.run {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  overflow: hidden;
}

.run.run-pass { border-left: 3px solid var(--run-pass-border); }
.run.run-fail { border-left: 3px solid var(--run-fail-border); }

details > summary { list-style: none; }
details > summary::-webkit-details-marker { display: none; }

.run-summary {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 18px;
  cursor: pointer;
  user-select: none;
  flex-wrap: wrap;
}

.run-summary:hover { background: rgba(0,0,0,.02); }
@media (prefers-color-scheme: dark) {
  .run-summary:hover { background: rgba(255,255,255,.03); }
}

.run-chevron {
  font-size: 11px;
  color: var(--text-muted);
  transition: transform .15s;
  flex-shrink: 0;
}
details[open] .run-chevron { transform: rotate(90deg); }

.run-title {
  font-weight: 600;
  font-size: 14px;
  flex-shrink: 0;
}

.badge-latest {
  font-size: 10px;
  font-weight: 700;
  background: var(--accent);
  color: #fff;
  padding: 1px 6px;
  border-radius: 99px;
  text-transform: uppercase;
  letter-spacing: .05em;
  vertical-align: middle;
  margin-left: 4px;
}

.run-time {
  font-size: 13px;
  color: var(--text-muted);
  font-variant-numeric: tabular-nums;
  flex-shrink: 0;
}

.run-badges { display: flex; gap: 6px; flex-shrink: 0; }

.badge {
  font-size: 12px;
  font-weight: 600;
  padding: 2px 8px;
  border-radius: 99px;
}
.badge-pass { background: var(--pass-bg); color: var(--pass); }
.badge-fail { background: var(--fail-bg); color: var(--fail); }

.run-pct {
  margin-left: auto;
  font-size: 13px;
  font-weight: 600;
  color: var(--text-muted);
  flex-shrink: 0;
}

/* ── Test table ── */

.run-body {
  border-top: 1px solid var(--border);
  overflow-x: auto;
}

.test-table {
  width: 100%;
  border-collapse: collapse;
}

.test-table th {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .07em;
  color: var(--text-muted);
  padding: 8px 12px;
  text-align: left;
  background: var(--bg);
  border-bottom: 1px solid var(--border);
}

.test-table td {
  padding: 9px 12px;
  border-bottom: 1px solid var(--border);
  vertical-align: middle;
}

.test-table tbody tr:last-child td { border-bottom: none; }

.test-table tbody tr:hover { background: rgba(0,0,0,.015); }
@media (prefers-color-scheme: dark) {
  .test-table tbody tr:hover { background: rgba(255,255,255,.03); }
}

.col-file { font-family: var(--mono); font-size: 13px; }
.col-status { width: 90px; }
.col-time { width: 200px; color: var(--text-muted); font-size: 13px; font-variant-numeric: tabular-nums; }
.col-dur  { width: 90px;  color: var(--text-muted); font-size: 13px; font-variant-numeric: tabular-nums; }

.status-dot {
  display: inline-block;
  width: 7px; height: 7px;
  border-radius: 50%;
  margin-right: 6px;
  vertical-align: middle;
}
.success .status-dot { background: var(--pass); }
.failure .status-dot { background: var(--fail); }
.success a { color: var(--pass); }
.failure a { color: var(--fail); }
"""

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>E2E Test Report</title>
  <style>{css}</style>
</head>
<body>
<div class="container">
  <header class="report-header">
    <h1>E2E Test Report</h1>
    <div class="stats-row">
      <div class="stat-card">
        <span class="value">{total_runs}</span>
        <span class="label">Runs</span>
      </div>
      <div class="stat-card">
        <span class="value">{total_files}</span>
        <span class="label">Files / run</span>
      </div>
      <div class="stat-card pass">
        <span class="value">{total_passed}</span>
        <span class="label">Passed</span>
      </div>
      <div class="stat-card fail">
        <span class="value">{total_failed}</span>
        <span class="label">Failed</span>
      </div>
    </div>
  </header>
  <main class="runs">
{runs_html}
  </main>
</div>
</body>
</html>
"""

RUN_TEMPLATE = """\
    <section class="run {run_class}">
      <details {open_attr}>
        <summary class="run-summary">
          <span class="run-chevron">▶</span>
          <span class="run-title">Run #{run_num}{latest_badge}</span>
          <span class="run-time">{run_time}</span>
          <span class="run-badges">{badges}</span>
          <span class="run-pct">{pct}%</span>
        </summary>
        <div class="run-body">
          <table class="test-table">
            <thead>
              <tr>
                <th class="col-file">File</th>
                <th class="col-status">Status</th>
                <th class="col-time">Start Time</th>
                <th class="col-dur">Duration</th>
              </tr>
            </thead>
            <tbody>
{rows_html}
            </tbody>
          </table>
        </div>
      </details>
    </section>"""

ROW_TEMPLATE = """\
              <tr class="{status}">
                <td class="col-file"><a href="{source_href}">{short_name}</a></td>
                <td class="col-status"><span class="status-dot"></span><a href="{timeline_href}">{status}</a></td>
                <td class="col-time">{start_time}</td>
                <td class="col-dur">{duration_s}s</td>
              </tr>"""


def render(rows: list[dict]) -> str:
    groups: dict[int, list[dict]] = defaultdict(list)
    for row in rows:
        groups[row["timestamp"]].append(row)

    sorted_ts = sorted(groups.keys(), reverse=True)

    all_passed = sum(1 for r in rows if r["status"] == "success")
    all_failed = len(rows) - all_passed
    files_per_run = max((len(v) for v in groups.values()), default=0)

    runs_parts: list[str] = []
    for i, ts in enumerate(sorted_ts):
        run_rows = sorted(groups[ts], key=lambda r: r["short_name"])
        passed = sum(1 for r in run_rows if r["status"] == "success")
        failed = len(run_rows) - passed
        pct = round(passed / len(run_rows) * 100, 1) if run_rows else 0

        badges = f'<span class="badge badge-pass">{passed} passed</span>'
        if failed:
            badges += f' <span class="badge badge-fail">{failed} failed</span>'

        rows_parts = [ROW_TEMPLATE.format(**r) for r in run_rows]

        run_num = len(sorted_ts) - i  # oldest = #1
        latest_badge = ' <span class="badge-latest">latest</span>' if i == 0 else ""

        runs_parts.append(
            RUN_TEMPLATE.format(
                run_class="run-pass" if failed == 0 else "run-fail",
                open_attr="open" if i == 0 else "",
                run_num=run_num,
                latest_badge=latest_badge,
                run_time=datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S"),
                badges=badges,
                pct=pct,
                rows_html="\n".join(rows_parts),
            )
        )

    return HTML_TEMPLATE.format(
        css=CSS,
        total_runs=len(sorted_ts),
        total_files=files_per_run,
        total_passed=all_passed,
        total_failed=all_failed,
        runs_html="\n".join(runs_parts),
    )


# ── Entry point ────────────────────────────────────────────────────────────────


def main() -> None:
    report_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent.parent / "reports" / "e2e"
    index = report_dir / "index.html"

    if not index.exists():
        print(f"[gen-e2e-report] Nothing to do: {index} not found", file=sys.stderr)
        sys.exit(0)

    raw = index.read_text(encoding="utf-8")
    rows = parse_rows(raw)
    if not rows:
        print("[gen-e2e-report] No test rows found in report (keeping Hurl index.html unchanged).", file=sys.stderr)
        sys.exit(0)

    index.write_text(render(rows), encoding="utf-8")
    print(f"[gen-e2e-report] Rewrote {index} ({len(rows)} rows across {len(set(r['timestamp'] for r in rows))} runs)")


if __name__ == "__main__":
    main()
