sandboxTemplate:
  name: treadstone-sandbox
  image: enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:latest
  containerPort: 8080
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 512Mi

warmPool:
  enabled: false
  replicas: 1
